# Verifying torch installation

* **Command** `conda install pytorch torchvision torchaudio`

* **Note:** Works only with python version less than 3.11

In [1]:
import torch
print(torch.__version__)

2.5.1


In [3]:
torch.ones(3), torch.ones(4)

(tensor([1., 1., 1.]), tensor([1., 1., 1., 1.]))

In [4]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:

points[0] = 1.0
points[1] = 9.0
points[2] = 6.0
points[3] = 3.0
points[4] = 7.0
points[5] = 2.0

points

tensor([1., 9., 6., 3., 7., 2.])

In [8]:
float(points[0]), float(points[1])


(1.0, 9.0)

In [11]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(points)
print("Shape: ",points.shape)
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])
Shape:  torch.Size([3, 2])


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [12]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points[0, 1]

tensor(4.)

In [13]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

/var/folders/ml/rd5kt59x51z3wbypqjnb36hr0000gn/T/ipykernel_20939/1455166040.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [17]:
points.stride()

# stride is a tuple indicating the number of elements in the storage that have to be 
# skipped when the index is increased by 1 in each dimension

(2, 1)

In [21]:
zero_points = torch.ones((5,3))
print(zero_points)
zero_points.stride()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


(3, 1)

# Comparing clone process First cell , modifying without cloning

points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
print("second_point ",second_point)
points

In [24]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

# Transposing

In [26]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [29]:
points_t = points.t()
print(points_t)


tensor([[1., 2., 3.],
        [4., 1., 5.]])


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [32]:
id(points.storage()) == id(points_t.storage())

False

In [34]:
points_t2 = points_t.clone()
print(points_t2)
id(points_t.storage()) == id(points_t2.storage())

tensor([[1., 2., 3.],
        [4., 1., 5.]])


True

In [41]:
some_tensor = torch.ones(3, 4, 5)
print(some_tensor.shape)
print("stride: ",some_tensor.stride())
some_tensor

torch.Size([3, 4, 5])
stride:  (20, 5, 1)


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [42]:
some_tensor_t = some_tensor.transpose(0, 2)
print(some_tensor_t.shape)
print("stride: ",some_tensor_t.stride())

print(some_tensor_t)

torch.Size([5, 4, 3])
stride:  (1, 5, 20)
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


# Definition :

A tensor whose values are laid out in the storage starting from the rightmost dimension
onward (moving along rows for a 2D tensor, for example) is defined as being contiguous.
Contiguous tensors are convenient because you can visit them efficiently and
in order without jumping around in the storage.

In [45]:
print(some_tensor.is_contiguous())
print(some_tensor_t.is_contiguous())

True
False


# Here’s a list of the possible values for the dtype argument:
* 􀂃 torch.float32 or torch.float—32-bit floating-point
* 􀂃 torch.float64 or torch.double—64-bit, double-precision floating-point
* 􀂃 torch.float16 or torch.half—16-bit, half-precision floating-point
* 􀂃 torch.int8—Signed 8-bit integers
* 􀂃 torch.uint8—Unsigned 8-bit integers
* 􀂃 torch.int16 or torch.short—Signed 16-bit integers
* 􀂃 torch.int32 or torch.int—Signed 32-bit integers
* 􀂃 torch.int64 or torch.long—Signed 64-bit integers

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

print(double_points)
print(short_points)
print('short_points dtype: ',short_points.dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
short_points dtype:  torch.int16


In [51]:
# Two ways to create tensors
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
print("--- Method one ---")
print(double_points)
print(short_points)

double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print("--- Method two ---")
print(double_points)
print(short_points)

--- Method one ---
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
--- Method two ---
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [53]:
points = torch.randn(10, 2) # randn initializes the tensor elements to random numbers between 0 and 1.

print(points)
short_points = points.type(torch.short)
short_points

tensor([[ 0.7148,  0.5760],
        [-2.3966, -0.0519],
        [ 0.3635, -0.6590],
        [ 0.5055, -1.7763],
        [ 0.1514, -0.0449],
        [-0.7855, -0.0933],
        [-1.2419, -1.6029],
        [ 0.4202, -0.3481],
        [-1.6817, -0.8045],
        [ 1.1054, -0.8688]])


tensor([[ 0,  0],
        [-2,  0],
        [ 0,  0],
        [ 0, -1],
        [ 0,  0],
        [ 0,  0],
        [-1, -1],
        [ 0,  0],
        [-1,  0],
        [ 1,  0]], dtype=torch.int16)

In [54]:
points[:] # All points

tensor([[ 0.7148,  0.5760],
        [-2.3966, -0.0519],
        [ 0.3635, -0.6590],
        [ 0.5055, -1.7763],
        [ 0.1514, -0.0449],
        [-0.7855, -0.0933],
        [-1.2419, -1.6029],
        [ 0.4202, -0.3481],
        [-1.6817, -0.8045],
        [ 1.1054, -0.8688]])

In [55]:
points[1:, :] # All points after first row

tensor([[-2.3966, -0.0519],
        [ 0.3635, -0.6590],
        [ 0.5055, -1.7763],
        [ 0.1514, -0.0449],
        [-0.7855, -0.0933],
        [-1.2419, -1.6029],
        [ 0.4202, -0.3481],
        [-1.6817, -0.8045],
        [ 1.1054, -0.8688]])

In [57]:
points[2:, 1] # All column after second row

tensor([-0.6590, -1.7763, -0.0449, -0.0933, -1.6029, -0.3481, -0.8045, -0.8688])

In [58]:
points[3:, 0] # All row after third row

tensor([ 0.5055,  0.1514, -0.7855, -1.2419,  0.4202, -1.6817,  1.1054])

In [60]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

#note: The returned array shares an underlying buffer with the tensor storage.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [62]:
points_bk = torch.from_numpy(points_np)
id(points_bk.storage()) == id(points.storage())

# Note: uses the same buffer-sharing strategy

True

# Serializing Tensor

In [69]:
!ls data

ourpoints.t


In [72]:
points = torch.randn(10, 2) # randn initializes the tensor elements to random numbers between 0 and 1.
points

tensor([[ 0.1468,  0.2638],
        [ 0.7427,  1.9481],
        [-1.5268,  0.1972],
        [-0.9786,  0.0123],
        [-0.3881, -1.4031],
        [-0.8270, -2.5110],
        [ 1.8079, -2.2073],
        [ 1.9363,  0.0891],
        [-1.1921, -0.8676],
        [ 1.6561,  0.9856]])

In [73]:
# first way

torch.save(points, 'data/ourpoints.t')

# second way

with open('data/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [77]:
points = torch.load('data/ourpoints.t')
print(points)

#second way to read from file

with open('data/ourpoints.t','rb') as f:
    points = torch.load(f)


# Note:  This technique allows you to save tensors quickly in case you only want to load them
# with PyTorch, but the file format itself isn’t interoperable. You can’t read the tensor
# with software other than PyTorch. Depending

tensor([[ 0.1468,  0.2638],
        [ 0.7427,  1.9481],
        [-1.5268,  0.1972],
        [-0.9786,  0.0123],
        [-0.3881, -1.4031],
        [-0.8270, -2.5110],
        [ 1.8079, -2.2073],
        [ 1.9363,  0.0891],
        [-1.1921, -0.8676],
        [ 1.6561,  0.9856]])


/var/folders/ml/rd5kt59x51z3wbypqjnb36hr0000gn/T/ipykernel_20939/3269304.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load('data/ourpoints.t')
/var/fol

# Alternative way to save the tensors 

**HDF5** is a portable, widely supported format for representing serialized multidimensional
arrays, organized in a nested key-value dictionary. Python supports HDF5
through the h5py library7, which accepts and returns data under the form of NumPy
arrays.

`conda install h5py`


In [79]:
import h5py
f = h5py.File('data/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [83]:
f = h5py.File('data/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = torch.from_numpy(dset[:])
f.close()
print(last_points)

tensor([[ 0.1468,  0.2638],
        [ 0.7427,  1.9481],
        [-1.5268,  0.1972],
        [-0.9786,  0.0123],
        [-0.3881, -1.4031],
        [-0.8270, -2.5110],
        [ 1.8079, -2.2073],
        [ 1.9363,  0.0891],
        [-1.1921, -0.8676],
        [ 1.6561,  0.9856]])


# Utilizing GPU

In [ ]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')

# second way


points_gpu = points.to(device='cuda')
points_gpu = points.to(device='cuda:0')

In [ ]:
points = 2 * points # Operation performed in CPU
points_gpu = 2 * points.to(device='cuda') # Operation performed in GPU

In [ ]:
# Move tensor back to CPU

points_cpu = points_gpu.to(device='cpu')

points_gpu = points.cuda() # defaults to cuda id : 0
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()